services:
  - type: web
    name: webtest-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-level debug --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DB_SERVER
        value: carlweb-server.database.windows.net
      - key: DB_DATABASE
        value: CarlWeb
      - key: DB_USERNAME
        value: carluser
      - key: DB_PASSWORD
        sync: false  # 從 Render 的環境變數中獲取
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: TZ
        value: Asia/Taipei
    domains:
      - webtest-api.onrender.com